#+TITLE: PPT 汇报
#+AUTHOR: thwzjx
#+LATEX_HEADER: \usepackage{xeCJK}
#+LATEX_COMPILER: xelatex
#+STARTUP: indent
* 地方政府经济行为
** 为什么要研究地方政府经济行为以及如何研究地方政府经济
*** 现实问题
  从国内形势来看，一方面，中国面临着人口红利消失、劳动力成本上升、大量制造业向其他低成本国家转移和出口下降等现实因素；另一方面，不平衡、不充分的发展已成为制约人民福利水平提升的重要因素，在两个一百年目标的实现过程中，地方政府仍然面临发展经济的压力，在此过程中，正确的认识和规范地方政府经济行为仍具有重要意义。\\
同时在中国改革开放以来，
*** 地方政府的独特地位
    我们通常采用两个指标来描述一个政府的规模大小，一个指标是政府所控制的财政支出，另一个则是政府的人员规模，那么我们就从这两个指标来看地方政府的地位是怎样的
   + 地方财政支出的比例一直处于高水平
   + 财政收入方面也是地方政府控制多于中央政府控制的
     #+begin_quote
     由图表可以看出
     #+end_quote
   + 地方政府在人事任命上的独立
     #+begin_quote
在全国所有的政府公务员里，中央公务员占比不到7%，而剩下的93%都是地方政府所雇用的公务员
     #+end_quote
   + 中国绝大多数产品的计划和配置权利是高度分散在各级地方政府手里
     #+begin_quote
     中国中央控制的产品种类只有600个，而苏联是5500个
     改革开放之初，中国2000个县几乎都拥有生产农机的国有企业，300个县有钢铁厂，20多个省的国有企业生产汽车或拖拉机的整机或配件，
     这与其他的计划经济体制的国家形成了鲜明的对比
     #+end_quote
   进入改革开放之后，地方政府的地位更加特殊，并且随着地方政府的权力的不断上升，中央和地方的关系不再是改革开放以前的命令和服从的关系，更多的演变为一种协商、谈判的关系。
   #+begin_quote
分税制改革是其中的典型案例，中央试图从财政包干制转向分税制，以大幅提高中央财政占国民经济中的比重和占全国财政收入的比重，由于这触及了许多发达省份的利益，开始，中央遇到的地方阻力较大。为了说服地方官员，当时的国务院总理朱镕基与各个省、市、自治区的领导进行一对一谈判，有时分歧太大，最终不欢而散。经过多轮艰苦的谈判和协商，中央做出了让步，通过税收返还的办法保证各个省、市、自治区1994年的财政收入不低于1993年的水平，还有一些安抚措施，分税制才得以顺利实施。
   #+end_quote
** 区域竞争与合作
*** 地方保护主义

在计划体制下地方政府主要听命于中央计划的安排，各种重要的经济管理决策权(如基建投资权、物资调配权)也掌握在中央部委手中，地方政府能够决策和控制的范围比较有限。从70年代初开始，中央强调各省区经济尽量建立一个工业体系完备、相对自给自足的经济。在这种情形之下，当然谈不上区域经济的竞争与合作问题。自80年代以来，随着中央计划管理权力的大量下放，政府间财政包干制的推行，以及政治锦标赛从过去的政治路线标准向强调经济增长的标准的过渡，地方官员的激励和行为发生了根本性的变化。这些变化的一个重要方面就是区域经济竞争日益加强。我国学术界喜欢用“诸侯经济”来概括地方政府主导下的区域经济，如果援用这说法，可以说中国区域经济的互动关系逐渐从被动的“诸侯割据”阶段到“诸侯争霸”的阶段。而且值得注意的一个现象是，不仅省级区域之间竞争激烈，以经济带和都市圈(如长三角、珠三角、京津唐)为单位的跨省“抱团“竞争近年来也越演越烈。\\
随着中国经济日趋开放，市场化进程的加快，生产要索的跨区流动日益絮、企业跨区兼并收购现象也开始变得普遍起来、这些变化都在有效降低中国省区经济的相对封闭的程度，扩大省区之间的生产要素的横向流动。我们也能够观察到一些地区的地方政府在自感组建区城性的合作机构，试图谋求“双赢“和“多赢”的局面。然而，地区间的市场封锁和保护问题仍然存在。并没有随着中国经济的市场化的进程自然消失，在一定范围内还表现得非常严重.0根据一项国际学者的研究结果，在1987年至1997年间.中国各省区一方面对国际市场不断开放， 省区的对外开放度(即省区的进出口总额占GDP的比例) 平均从14%上升到37%，另一方面，对内却不断走向区域封锁.1997年消费者从省内生产者购买的商品额要27倍于从外省生产者购买的商品额，这一数值在1992年和1987年分别为16和12倍。这相当于省际贸易的关税税率从1987年的37%上升到了51%。中国省际之间的贸易壁垒非常接近于主权国家之间的水平，但显然高于主权国家内部的水平。\\
地方保护主义在不同时期有不同的表现形式。80年代实行行政性分权和财政包干体制、地方官员晋升也开始注重经济发展绩效，地方逐渐从计划体制下被动接受中央计划的安排到积极主动地谋取本地区的经济利益这一时期，计划经济仍然占主导，市场力量尚不发达，许多日需品和原材料还是属于短缺商品，地方保护主义主要表现在争夺短缺性的原材料和保护本地市场。当投资需求膨胀和经济济过热时，省区政府就利用区域性垄断和封锁手段.阻止本地区短缺性原材料运往外地，以保障本地企业的满负荷运转；当宏观经济紧缩、需求疲软时，又禁止外地商品进人本地市场销售，以保护本地企业。整个80年代爆发了数次区域之间的贸易封锁战和资源争夺战，比如“生猪大战”、“羊毛大战”“蚕茧大战”等等。1985年至1986年，由于羊绒和羊毛的价格飞涨，我国北方羊绒区爆发了“羊绒大战”，我国的羊毛主产区内蒙古，吉林、新疆、山西等地无一例外恢复了羊毛的统购统销、在省区交界地区、到处都设立羊毛收购站，大家虎视眈眈，围追堵截，以防羊毛流出本省，1985年仅内蒙古赤峰市在与辽宁、河北交界地区就设立了106个1985年又增加了70多个，1988年作为长期贸易伙伴的粤、湘、赣三省、为了保护各自的经济利益，分别制定了“边界壁垒”政策：湖南省对粮食、蚕茧等12种物质实行禁运：江西省对大米、生猪实行禁运，广东省对食糖、橡胶实行禁运。其他地区也有类似的事件发生。[2]90年代以来随着计划体制的瓦解，产品短缺的局面逐渐转变为产品过剩，此时的地方保护主义更多表现为对本地企业和市场的保护，限制外地商品流入。例如1997年辽宁省盖州市强行要求全市45家酒类批发零售企业与当地的龙洋啤酒厂签订协议，专卖该厂的“瑞雪”啤酒，违者吊销营业执照并重罚2万元。几乎在同一时间，河南省固始县则明文规定：“为了保护本地化肥工业生产，禁止任何单位和个人(包括供销社系统)从外地购进碳氨。”违者除没收商品和“非法”所得外，还要予以重处并追究乡、镇主管干部的行政和经济责任。\\
地方保护主义近年来呈现两个特点\\
1. 过去地方保护的是本地商品市场不受外地商品的竞争
2. 现在保护的重点是逐渐向服务业和生产要素过度。
*** 地方保护主义原因
    + 经济参与人
      #+begin_quote
他们作为经济参与人，即像任何经济主体一样关注经济利益，20世纪80年代以来的行政性分权和财政包干强化了地方政府的经济动机；地方经济的发展可以带来248更多的财税，地方官员能够支配的财源也随之增加，这比“统收统支”的财政体制更能促进地方官员去创造更多的财政收人。
      #+end_quote
    + 政治参与人
      #+begin_quote
但是更为关键的，这些地方官员同时也是“政治参与人”，他们关注自己的政治晋升和政治收益。各地的官员不仅在经济上为财税和利润而竞争，同时也在“官场"上为晋升而竞争，20世纪80年代初期实施的领导干部选拔和晋升标准的重大改革使地方官员的晋升与地方经济发展绩效挂钩.使得地方官员的个人利益(政治晋升)与区域经济增长与发展紧密相连，从而达到机制设计上的激励相容的效果。地区的GDP增长、财政收人增长、外资的引人直接进人到地方官员绩效考核体系，成为地方官员晋升的重要标准，对于地方官员来说，官场竞争比经济竞争更为重要，经济竞争在很多场合实现官场竞争的一个手段。首先， GDP增长、财政收人和吸引外资直接与官员晋升挂钩，地区之间围绕这些指标的竞争本身就是官场竞争的一部分；其次，激烈的官场晋升竞争会进一步强化地方官员的财税激励和对吸引外资的重视，因为地方官员只有自主掌握了足够的经济资源，才能更好地实施其经济增长战略，提高本地区的经济排名.过去大量的研究从市场和经济竞争的逻辑出发强调行政性分权和地方官员的财政激励对区域间经济互动的影响。这种研究角度只注重于我国地方官员的第一种特征，而忽略了地方官员的第二种特征及其影响。
      #+end_quote
这不仅仅是在经济范围内是这样，同样地，在地区交界之处的污染问题也深受这样的困扰。

*** 解决办法与意见

+ 要真正规范政府行为，做到科学、民主、依法执政
#+begin_quote
按照布坎南的“寻租”理论，减少、放松甚至在某些方面取消政府管制，提高经济、市场自由度，是提高资源配置效率、提高经济增长竞争力、消除寻租、腐败的好办法。从改革开放以来一直推行的以精简政府机构、人员为特征的机构改革，提出打造精简、统一、效能政府到十六届四中全会提出的加强“执政能力”建设的要求，从2004年7月1日正式实施的以限制约束政府有关职能为特征的《行政许可法》，到2011年11月14日国务院召开的深入推进行政审批制度改革工作电视电话会议上提出的进一步清理、减少和调整行政审批事项，推进政府职能转变，强化对权力运行的监督制约，推进法治政府、服务型政府和反腐倡廉建设。这些举措都充分体现了我们党和政府“以人为本”、“执政为民”的鲜明态度和决心，体现了我国政府将努力推行科学执政、民主执政、依法执政的愿望和决心。但是从目前地方保护主义、行业垄断依然顽固来看，要实现这一目标还很艰巨。
#+end_quote
+ 建立合理的利益机制，确保政府及公职人员正当合法利益的实现
#+begin_quote
首先，要通过合理的利益机制消除、抵御造假者的不正当利益对政府官员的诱惑，从而从根源上遏制以权钱交易为主要表现形式的地方政府保假护劣的行为现象。要在国家公职人员晋升任用方面坚持功绩制原则，通过晋升把政绩与利益有机结合起来，要把国家公职人员对管理效率的追求与其自身利益紧密联系起来。其次，要加快制度建设，加大惩罚力度，使“寻租”腐败、使保护假冒伪劣行为成为一种高成本、高风险、高代价的行为，在利益的权衡上成为得不偿失的行为，使地方保护主义（也即小利益集团的一种腐败、寻租）不再有制度上、政策上的合理性。
#+end_quote
+ 树立绿色GDP观念和科学的干部考核体系
 #+begin_quote
地方保护主义追求地方自我利益的最大化，这种“利益”远远不仅仅是政府公职人员的经济利益，很大程度上是自我“政绩、仕途”的利益。前几年不少地方出现的高增长低发展，或者高增长不发展，甚至高增长负发展的现象，以及一些对经济和社会产生巨大负作用的黄、赌、毒、黑、污染及假冒伪劣都在创造这些地方的GDP。根本原因就是 “GDP拜物教”观念，GDP出官。因此，一定要把转型发展的理念，把经济与社会和谐、可持续发展的绿色GDP观念，把诚信道德教育、法制建设，把打假治劣、维护市场秩序，把依法行政、科学、民主执政纳入到各级地方政府及每个政府工作人员的考核体系之中。因为假冒伪劣是典型的信用缺失行为，而地方保护主义对假冒伪劣现象的纵恿、庇护，既是严重的行政不作为，又是对政府信用、国家公信的践踏。因此要进一步强化对各级政府实行信用缺失、假冒伪劣重大事件的问责制，信用信息传递、披露、评价及惩戒体系
#+end_quote
+ 加大政务公开力度，增加政府工作透明度
 #+begin_quote
公开是一种最好的监督形式。我们把公开作为监督权力滥用的主要手段，主要是针对权力行使“暗箱”操作的神秘化弊端而提出的。只有政务公开，公众才能进行有效监督。政府应主动接受监督，将公众监督政府的情况及政府接受监督并处理的情况公开，使公众感受到自己在监督政府、反腐败中的作用，切实感到参政、议政的作用，发挥公众监督的强约束作用，避免“合乎理性的无知”行为、“堂而皇之的造假”行径及“坏车驱逐好车”的市场逆淘汰现象的出现。此外，还要采取措施，包括精神或物质上的鼓励措施，使公众在经济成本——收益分析后会积极参与监督政府工作、监控假冒伪劣行为和“寻租”、腐败现象。
#+end_quote
